### PR TITLE
Fix sharing issue

### LINKED ISSUE #93: A resource doesn't appear for its owner when a shared user removes the read and write rights to all groups
Storage : FileStore and File System

### How to reproduce
- Create a resource by a user **A** (the owner)
- Share the resource with read AND write rights with a group **G**
- Login with a user **B** who belongs to group **G**
- User **B** has the right to share the resource as well
- With user **B** remove the read AND write rights from all groups of this resource
- The resource is fetched with _GET list_ for user **B**, but user **B** should no longer see this resource.
- Login now with the user **A**. The resource is not fetched with _GET list_ but user **A** is its owner, so it should appear in the list

### PR DESCRIPTION
**Pull request by alainbodiguel**
Fix #93

### CODE REVIEW

File: arlas-persistence-core/src/main/java/io/arlas/persistence/server/core/PersistenceService.java [hunk 1]
```diff
@@ -64,7 +64,9 @@ Data deleteById(String id,
 
     static List<String> getGroupsForZone(String zone,
                                          IdentityParam identityParam) {
-        return identityParam.groups;
+        return identityParam.groups.stream()
+                .filter(g -> !g.startsWith("group/preview/") && !g.startsWith("group/i18n/"))
```
Comment (MohamedHamouGisaia) [inline arlas-persistence-core/src/main/java/io/arlas/persistence/server/core/PersistenceService.java:68]: I think there is also : group/tour
